# prd.yml
services:
  mailmerge-prd:
    image: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"   # from .env written by workflow
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mailmerge-postgresql-prd:5432/mailmerge
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://mailmerge-postgresql-prd:5432/mailmerge
      - SPRING_DATASOURCE_USERNAME=mailmerge
      - SPRING_DATASOURCE_PASSWORD=
      - JHIPSTER_SLEEP=15
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "9090:8080"   # external:internal
    depends_on:
      - mailmerge-postgresql-prd
    networks:
      - app-network

  mailmerge-postgresql-prd:
    image: postgres:14.5
    restart: always
    # uncomment + set an absolute host path if you want data to persist across deploys
    # volumes:
    #   - /home/ubuntu/prd/volumes/jhipster/mailmerge/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mailmerge
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=mailmerge
      - POSTGRES_HOST_AUTH_METHOD=trust
    # DB is only used internally; no need to expose it publicly
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

